<?php
include("last_access.inc");
?>
<!--
<hr>
<font size="1">
This part of the Intranet is developed by Charlie MAO<br>
<br>
Research Labrotories of Australia<br>
7 Valetta Rd<br>
Kidman Park<br>
SA 5025<br>
Australia<br>
Tele: 61-8-83521322<br>
Fax:   61-8-83521359<br>
Return to <a href="http://intranet.rla.com.au/">Intranet</a>
or visit <A href="http://www.rla.com.au">Web Page.</A><Br>
Please email your comments to <a href="mailto:
<?php 
	include("find_admin_ip.inc");
	echo $adminname;
?>
@rla.com.au">Intranet Developer</a>.<br>
Intranet was last modified on 
<?php
print (date("F d, Y"));
?>
<hr>
</font>
-->