<html>
<?php
	$prohibit_chr_in_keyword[] = ",";
	$prohibit_chr_in_keyword[] = ".";
	$prohibit_chr_in_keyword[] = ":";
	$prohibit_chr_in_keyword[] = ";";
	$prohibit_chr_in_keyword[] = '"';
	$prohibit_chr_in_keyword[] = "'";
	$prohibit_chr_in_keyword[] = "!";
	$prohibit_chr_in_keyword[] = "?";
	$prohibit_chr_in_keyword[] = "<";
	$prohibit_chr_in_keyword[] = ">";
	$prohibit_chr_in_keyword[] = "/";
	$prohibit_chr_in_keyword[] = "\\";
	$prohibit_chr_in_keyword[] = "*";
	$prohibit_chr_in_keyword[] = "@";
	$prohibit_chr_in_keyword[] = "$";
	$prohibit_chr_in_keyword[] = "%";
	$prohibit_chr_in_keyword[] = "^";
	$prohibit_chr_in_keyword[] = "&";
	$prohibit_chr_in_keyword[] = "*";
	$prohibit_chr_in_keyword[] = "(";
	$prohibit_chr_in_keyword[] = ")";
	$prohibit_chr_in_keyword[] = "-";
	$prohibit_chr_in_keyword[] = "+";
	$prohibit_chr_in_keyword[] = "|";
	$prohibit_chr_in_keyword[] = "~";
	
	$prohibit_chr_in_abstract[] = "/";
	$prohibit_chr_in_abstract[] = "\\";
?>
</html>