        <option>VARCHAR
        <option>CHAR
        <option>DATE
        <option>TIMESTAMP
        <option>SET
        <option>
		 <option>TINYINT
        <option>SMALLINT
        <option>MEDIUMINT
        <option>INT
        <option>INTEGER
		 <option>BIGINT
		 <option>
        <option>REAL
        <option>DOUBLE
        <option>FLOAT
        <option>DECIMAL
        <option>NUMERIC
        <option>
        <option>TIME
        <option>DATETIME
        <option>
        <option>TINYBLOB
        <option>BLOB
        <option>MEDIUMBLOB
        <option>LONGBLOB
        <option>
        <option>TINYTEXT
        <option>TEXT
        <option>MEDIUMTEXT
        <option>LONGTEXT
        <option>
        <option>ENUM
<!--<option>year -->
<!--
	 TINYINT					[(length)] 			[UNSIGNED] 			[ZEROFILL]
    SMALLINT					[(length)] 			[UNSIGNED] 			[ZEROFILL]
    MEDIUMINT					[(length)] 			[UNSIGNED] 			[ZEROFILL]
    INT						[(length)] 			[UNSIGNED] 			[ZEROFILL]
    INTEGER					[(length)] 			[UNSIGNED] 			[ZEROFILL]
    BIGINT						[(length)] 			[UNSIGNED] 			[ZEROFILL]
    REAL						[(length,decimals)] 	[UNSIGNED] 			[ZEROFILL]
    DOUBLE						[(length,decimals)] 	[UNSIGNED] 			[ZEROFILL]
    FLOAT						[(length,decimals)] 	[UNSIGNED] 			[ZEROFILL]
    DECIMAL(length,decimals) 						[UNSIGNED] 			[ZEROFILL]
    NUMERIC(length,decimals) 						[UNSIGNED] 			[ZEROFILL]
    CHAR(length) 				[BINARY]
    VARCHAR(length) 			[BINARY]
    Date
    Time
    TimeStamp
    DateTime
    TINYBLOB
    BLOB
    MEDIUMBLOB
    LONGBLOB
    TINYTEXT
    Text
    MEDIUMTEXT
    LongText
    ENUM(value1,value2,value3,...)
    SET(value1,value2,value3,...)
-->