<html>
<tr><th class=td1>psql Listing  commands </th>
    <td><select name="psql_listing_commands">
        <option>Aggregates  \da name
        <option>Comments  \dd name
        <option>Databases  \l
        <option>Functions  \df name
        <option>Indexes  \di name
        <option>Large objects  \dl name
        <option>Operators  \do name
        <option>Permissions  \z or \\dp name
        <option>Sequences  \ds name
        <option>System tables  \dS name
        <option>Table, index, view, or sequence \d name
        <option>Tables \dt name
        <option>Types  \dT name
        <option>Views  \dv name
    </option></select></th>
</tr>
</html>
