<html>
<tr><th class=td1>psql's query buffer commands</th>
    <td><select name="psql_query_buffer_commands">
        <option>Backslash help \?
        <option>Clear \r
        <option>Edit \e file
        <option>Execute \g or ; file or command
        <option>Include file \i file
        <option>Output to file/command \o file or command
        <option>Print \p
        <option>Quit \q
        <option>Run subshell \! command
        <option>SQL help \h topic
        <option>Show/save query history \s file
        <option>Write buffer to file \w file
    </option></select></th>
</tr>

</html>
