<html>
<?php
		$biref_description = trim($biref_description);
		$barcode = trim($barcode);
		if ($barcode == "") {
			$barcode = "NA";
		}
		$size_xyz_cm = trim($size_xyz_cm);
		$color = trim($color);
		$year_made = trim($year_made);
		$order_no = trim($order_no);
		$purchase_date = trim($purchase_date);
		$disposal = trim($disposal);
		$purchasing_price = trim($purchasing_price);
		$purchased_by = trim($purchased_by);
		$purchased_for = trim($purchased_for);
?>
</html>