<html>
<?php
	echo "email_name: $email_name.<br>";
	echo "logon_name: $logon_name.<br>";
	echo "title: $title.<br>";
	echo "first_name: $first_name.<br>";
	echo "middle_name: $middle_name.<br>";
	echo "last_name: $last_name.<br>";
	echo "userpwd: $userpwd.<br>";
	echo "priv: $priv.<br>";
	echo "myid: $myid.<br>";
	echo "myrootid: $myrootid.<br>";
	echo "yyyymmdd: $yyyymmdd.<br>";
	echo "myitem: $myitem.<br>";
	//echo "dbname: $dbname.<br>";
?>
</html>